CREATE TABLE `bd_role`(
    # 档口主、楼长、分拨、管理员
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '序号',
    `name` VARCHAR (10) NOT NULL DEFAULT '未知' COMMENT '名称',
    -- `parent` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父id',
    `group` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '组id',#普通用户组不会进入角色判断
    `content` VARCHAR (30) NOT NULL DEFAULT '' COMMENT '描述',
    PRIMARY KEY(`id`)
) DEFAULT CHARSET = UTF8 ENGINE = INNODB COMMENT '角色信息表';

CREATE TABLE `bd_role_right`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '序号',
    `role` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色',
    `right` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '权力',
    `content` VARCHAR (30) NOT NULL DEFAULT '' COMMENT '描述',
    PRIMARY KEY(`id`)
) DEFAULT CHARSET = UTF8 ENGINE = INNODB COMMENT '角色权力表';

CREATE TABLE `bd_right`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '序号',
    `name` VARCHAR (10) NOT NULL DEFAULT '未知' COMMENT '名称',#订餐、查订单、修改用户
    `content` VARCHAR (30) NOT NULL DEFAULT '' COMMENT '描述',
    PRIMARY KEY(`id`)
) DEFAULT CHARSET = UTF8 ENGINE = INNODB COMMENT '权力信息表';
